# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: The wise man builds no hopes for the future, entertains no regrets for the past.
- content: 既然目标是地平线 留给世界的只能是背影。
bottom_saying: 成长之美
# Content
excerpt_link: Read More

rss: /atom.xml

#highlightjs: vs
highlightjs: idea
google_analytics: UA-54861017-2
baidu_analytics: true

#Works
#works:
#- works_name: AAA
#  works_url: /
#- works_name: BBB
#  works_url: /atom.xml

#duoshuo name
#duoshuo: duoshuo_name

# Miscellaneous
github: https://github.com/francisar
twitter: https://twitter.com/cpf382607308
#facebook: https://www.facebook.com/
#google: https://google.com/
weibo: http://weibo.com/u/2465175025/home



#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More
widgets: 
- calendar
#Links
#links:
#- name: Kieran
#  link: http://go.kieran.top/
#- name: Name
#  link: http://domain.com/
